language: node_js

node_js:
  - "node"
  
install: 
  - npm install

script:
  - npm test
  - npm run build
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run deploy; fi

branches:
  except:
  - gh-pages